# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xuan', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='JiguiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jq', models.CharField(max_length=64)),
                ('zy', models.CharField(max_length=64)),
                ('ziy', models.CharField(max_length=64)),
                ('zs', models.CharField(max_length=64)),
                ('zb', models.CharField(max_length=64)),
                ('sh', models.CharField(max_length=64)),
                ('xz', models.CharField(max_length=64)),
                ('yong', models.CharField(max_length=64)),
                ('d', models.ManyToManyField(to='jigui.dx')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.JifangGroup')),
            ],
        ),
    ]
