# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiguiinfo',
            name='ctime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
