# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jigui', '0002_jiguiinfo_ctime'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiguiinfo',
            name='utime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
